#!/bin/bash

#SBATCH --account=emiliofe_74
#SBATCH --partition=gpu
#SBATCH --gres=gpu:v100:1
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=4
#SBATCH --mem=64G
#SBATCH --time=4:00:00
#SBATCH --chdir=/home1/mm_517/SocGFM_USC/SocGFM/src

module purge
eval "$(conda shell.bash hook)"
conda activate SocGFM

python run_GNNPlusLLM.py --dataset iran --device 0 --latent 128 --lr 1e-2 --early 40